import os
from dotenv import load_dotenv

load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = os.getenv("ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))
DATABASE_URL = os.getenv("DATABASE_URL")
SECRET_API_KEY = os.getenv("SECRET_API_KEY")
ID_KEY = os.getenv("ID_KEY")
FIRST_SUPERUSER_USERNAME= os.getenv("FIRST_SUPERUSER_USERNAME")
FIRST_SUPERUSER_PASSWORD= os.getenv("FIRST_SUPERUSER_PASSWORD")